/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:193fa823-dd3f-4a48-a93d-d2efc1e0094a",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_WAo5fvA5e",
    "aws_user_pools_web_client_id": "59v1ru1402mrp5c4lps940oak4",
    "oauth": {}
};


export default awsmobile;
